name: build
run-name: Triggered by ${{ github.event_name }} to ${{ github.ref }} by @${{ github.actor }}

on: [push]

jobs:
  go_build_job:
    runs-on: ubuntu-latest
    name: mpbench
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"
      - name: Build mpbench
        run: |
          go get .
          go build

  web_build_job:
    runs-on: ubuntu-latest
    name: web
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Build Dashboard
        run: |
          cd dashboard
          npm ci
          npm run build

  all:
    needs: [go_build_job, web_build_job]
    runs-on: ubuntu-latest
    name: all
    steps:
      - name: Build All
        run: echo "All builds completed successfully!"
